In [3]:
import duckdb 
import pandas as pd
import os
from datetime import datetime

In [4]:
con = duckdb.connect(database='dados_duckdb.db', read_only=False)

In [22]:
arquivo = 'z0019_2.csv'
data_ingestacao = datetime.now()
df = pd.read_csv('../landing/z0019_1.csv', sep=';')
df ['nome_arquivo'] = arquivo 
df ['data_ingestacao'] = data_ingestacao
df.head()

,NATBR,MAKT,WERKS,MAINS,LABST,nome_arquivo,data_ingestacao
0,10001,PARAFUSO,BT10,100,100,z0019_2.csv,2025-08-20 09:35:18.158888
1,10002,MARTELO,BT50,100,2500,z0019_2.csv,2025-08-20 09:35:18.158888
2,10003,CHAVE DE FENDA,B60,100,500,z0019_2.csv,2025-08-20 09:35:18.158888

In [23]:
con.execute("""
    CREATE TABLE IF NOT EXISTS bronze_produtos (
     NATBRO VARCHAR,
     MAKT   VARCHAR,
    WERKS VARCHAR,
    MAINS VARCHAR,
    LABST INTEGER,
    nome_arquivo	 VARCHAR,
    data_ingestacao TIMESTAMP    
               )
""")

In [25]:
con.execute("""INSERT INTO bronze_produtos
    SELECT * FROM df""")

In [29]:
resultado = con.execute("SELECT * FROM bronze_Z0019").fetchdf()
resultado.head()

,NATBRO,MAKT,WERKS,MAINS,LABST,nome_arquivo,data_ingestacao
0,10001,PARAFUSO,BT10,100,100,z0019_1.csv,2025-08-20 09:28:36.133547
1,10002,MARTELO,BT50,100,2500,z0019_1.csv,2025-08-20 09:28:36.133547
2,10003,CHAVE DE FENDA,B60,100,500,z0019_1.csv,2025-08-20 09:28:36.133547
3,10001,PARAFUSO,BT10,100,100,z0019_2.csv,2025-08-20 09:35:18.158888
4,10002,MARTELO,BT50,100,2500,z0019_2.csv,2025-08-20 09:35:18.158888

In [27]:
con.execute("""ALTER TABLE bronze_produtos RENAME TO bronze_Z0019""")

In [30]:
con.close()